server:
  port: 80
logging:
  config: classpath:logback.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.95.117.48:3306/wx?useUnicode=true&characterEncoding=utf8
    username: root
    password: '!QAZ2wsx'
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    type: com.alibaba.druid.pool.DruidDataSource

wx: 
  token: shotacon
  appid: wx1159f103330c7674 #wx653238f80b94017a
  appsecret: f1f7d7762f3417fd2ad0dc3bd8025aac #096f0d891a2cd23c591bff200ef91486
  EncodingAESKey: JdOWTwNGjpu0p0ipTEowGJM8kcKgtpsBZ2CAekhztLt